# Generated by Django 5.2.7 on 2025-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('garzon', 'Garzon'), ('cocina', 'Cocina'), ('gerencia', 'Gerencia')], max_length=20, null=True),
        ),
    ]
